In [1]:
a = [[2, 4, 6, 8, 10,15], [3, 6, 9, 12, 15], [4, 8, 12, 16, 20]]
for record in a:
    print(record)

[2, 4, 6, 8, 10, 15]
[3, 6, 9, 12, 15]
[4, 8, 12, 16, 20]


In [18]:
a = [ [2, 4, 6, 8 ], 
    [ 1, 3, 5, 7 ], 
    [ 8, 6, 4, 2 ], 
    [ 7, 5, 3, 1 ] ] 
          
for i in range(len(a)) : 
    for j in range(len(a[i])) : 
        print(a[i][j], end=" ")
    print() 

2 4 6 8 
1 3 5 7 
8 6 4 2 
7 5 3 1 


In [3]:
import numpy as np
a = np.array([1,2,3])
print(a)

a = np.array([(1,2,3),(1,526,66)])
print(a)

[1 2 3]
[[  1   2   3]
 [  1 526  66]]


In [1]:
import numpy as np
import time
import sys
s = range(2000)
print(sys.getsizeof(5)*len(s))
d=np.arange(2000)
print(d.size*d.itemsize)


56000
8000


In [2]:
import time
import sys
size=1000000
list1=range(size)
list2=range(size)
a1=np.arange(size)
a2=np.arange(size)
start=time.time()
result = [(x,y) for x,y in zip(list1,list2)]
print((time.time()-start)*1000)
start=time.time()
result = a1 +a2
print((time.time()-start)*1000)

101.16434097290039
33.71858596801758


In [6]:
import numpy as np
a=np.array([(1,2,3,5,6,8),(1,2,3,5,6,7)])
print(a)
a=a.reshape(6,2)
print(a)

[[1 2 3 5 6 8]
 [1 2 3 5 6 7]]
[[1 2]
 [3 5]
 [6 8]
 [1 2]
 [3 5]
 [6 7]]


In [7]:
a=np.array([(1,2),(4,5),(13,13)])
print(a)
print(a[0:2,1])

[[ 1  2]
 [ 4  5]
 [13 13]]
[2 5]


In [11]:
import numpy as np
a=np.linspace(1,5,20)
#a=np.random.randint(1,5,size=20)
print(a)
print(len(a))

[1.         1.21052632 1.42105263 1.63157895 1.84210526 2.05263158
 2.26315789 2.47368421 2.68421053 2.89473684 3.10526316 3.31578947
 3.52631579 3.73684211 3.94736842 4.15789474 4.36842105 4.57894737
 4.78947368 5.        ]
20


In [12]:
import numpy as np
a=np.array([(1,2,3,4,5,6,2564,985,1365)])
print(a.min())
print(a.max())
print(a.sum())
print(a.mean())

1
2564
4935
548.3333333333334


In [15]:
import numpy as np
a=np.array([(1,3,4),(5,6,8)])
print(a)
print(a.sum(axis=1))

[[1 3 4]
 [5 6 8]]
[ 8 19]


In [17]:
import numpy as np
a=np.array([(100,4,9),(36,49,64)])
print(np.sqrt(a))
print(np.std(a))

[[10.  2.  3.]
 [ 6.  7.  8.]]
32.7854981491648


In [1]:
import numpy as np
a=np.random.rand(10,100)
a

array([[6.30316783e-01, 4.59788462e-01, 6.17584016e-01, 1.84154035e-02,
        6.91853196e-01, 9.37381360e-01, 4.99672495e-01, 8.69174348e-01,
        4.79003940e-01, 8.03414741e-01, 8.78261221e-01, 1.50326051e-01,
        3.47141446e-01, 2.46645242e-01, 8.86083398e-01, 9.02775478e-01,
        9.87206200e-01, 1.23588646e-01, 3.00151766e-01, 8.32624873e-01,
        1.69680745e-01, 2.23472279e-02, 2.14915102e-02, 8.02953297e-01,
        6.33686699e-01, 5.73168603e-02, 1.39544848e-02, 5.65447059e-01,
        1.29680169e-01, 5.34899329e-01, 7.63102673e-01, 5.74290550e-01,
        6.33972126e-01, 3.67159478e-01, 2.58388868e-01, 1.34215289e-01,
        8.16194463e-01, 8.63004576e-02, 8.66016897e-01, 8.26256334e-01,
        4.31050661e-01, 5.12626423e-01, 3.85691881e-01, 2.47450723e-01,
        5.12917545e-01, 4.31648149e-01, 5.53318655e-01, 7.02889529e-01,
        7.78221478e-01, 2.14772798e-01, 7.92552010e-01, 7.04742359e-01,
        2.44411363e-01, 2.02445267e-01, 2.80146036e-01, 5.376469

In [6]:
import numpy as np
a=np.random.bytes(7)
a

b'\xfb\x85\x02`\x19\x92\xa3'

In [19]:
import numpy as np
a = np.array([(1,2,3,41,68,2),(1,2,3,5,6,8)])
print(a[1:2])
print(a)

[[1 2 3 5 6 8]]
[[ 1  2  3 41 68  2]
 [ 1  2  3  5  6  8]]


In [21]:
import numpy as np
a= np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [22]:
import numpy as np
arr = np.array([(1,2,3,41,68,2),(1,2,3,5,6,8)])
print(arr[0:2])
a

[[ 1  2  3 41 68  2]
 [ 1  2  3  5  6  8]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
import numpy as np
# Below are a quick examples

# Example 1: Create numpy arrays
arr = np.array([3, 5, 7, 9, 11, 15, 18, 22])

# Example 2: Use slicing a 1D arrays
arr2 = arr[1:6]
print(arr2)
# Example 3: Slice Starting from 3rd value to end
arr2 = arr[3:]
print(arr2)
# Example 4: Slice 0 to 4 index
arr2 = arr[:5]
print(arr2)
# Example 5: Use negative slicing
arr2 = arr[-4:-2]
print(arr2)
# Example 6: Use step value
arr2 = arr[::3]
print(arr2)
# Example 7: Use slicing with interval
arr2 = arr[3::4]
print(arr2)
# Example 8: Use slicing a 2D arrays
arr = np.array([[3, 5, 7, 9, 11],
               [2, 4, 6, 8, 10]])
arr2 = arr[1:,1:3]
print(arr2)
# Example 9: Slicing 3-D arrays
arr = np.array([[[3, 5, 7, 9, 11],
                 [2, 4, 6, 8, 10]],
                [[5, 7, 8, 9, 2],
                 [7, 2, 3, 6, 7]]])
arr2 = arr[0,1,0:2]
print(arr2)


[ 5  7  9 11 15]
[ 9 11 15 18 22]
[ 3  5  7  9 11]
[11 15]
[ 3  9 18]
[ 9 22]
[[4 6]]
[2 4]


In [14]:
# import numpy
import numpy as np

a = np.array([[10.2, 21.4, 3.6, 14.8], [1.0, 5.0, 10.0, 15.0]])
bins = np.array([1.0, 1.3, 2.5, 4.0, 10.0])

# using np.digitize() method
gfg = np.digitize(a, bins)

print(gfg)


[[5 5 3 5]
 [1 4 5 5]]


In [18]:
import numpy as np 
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
   
print ('First array:') 
print (a) 
print ('\n')  
   
print ('Second array:') 
print (b) 
print ('\n') 
   
print ('First Array + Second Array') 
print (a + b)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array:
[1. 2. 3.]


First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [1]:
import numpy as np
l1 = np.log(1e-50)
l2 = np.log(2.5e-50)
print("Logarithm of the sum of exponentiations:")
print(np.logaddexp(l1, l2))
print("Logarithm of the sum of exponentiations of the inputs in base-2:")
print(np.logaddexp2(l1, l2))

Logarithm of the sum of exponentiations:
-113.87649168120691
Logarithm of the sum of exponentiations of the inputs in base-2:
-113.59955522772194


In [2]:
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)
print("Division of the array inputs, element-wise:")
print(np.true_divide(x, 3))

Original array:
[0 1 2 3 4 5 6 7 8 9]
Division of the array inputs, element-wise:
[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ]


In [3]:
import numpy as np
x = np.arange(12).reshape((2, 6))
print("\nOriginal array:")
print(x)
r1 = np.percentile(x, 80, 1)
print("\n80th percentile for all elements of the said array along the second axis:")
print(r1)


Original array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

80th percentile for all elements of the said array along the second axis:
[ 4. 10.]


In [4]:
import numpy as np
x = np.array([0, 1, 3])
y = np.array([2, 4, 5])
print("\nOriginal array1:")
print(x)
print("\nOriginal array1:")
print(y)
print("\nPearson product-moment correlation coefficients of the said arrays:\n",np.corrcoef(x, y))


Original array1:
[0 1 3]

Original array1:
[2 4 5]

Pearson product-moment correlation coefficients of the said arrays:
 [[1.         0.92857143]
 [0.92857143 1.        ]]


In [5]:
import numpy as np
x = np.arange(12).reshape((2, 6))
print("\nOriginal array:")
print(x)
r1 =  np.median(x)
print("\nMedian of said array:")
print(r1)


Original array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

Median of said array:
5.5


In [7]:
import numpy as np
arr = np.array([30,60,90])

val_sin = np.sin(arr)
print("Sine value",val_sin)

val_cos = np.cos(arr)
print("Cosine value",val_cos)

val_tan = np.tan(arr)
print("Tangent value",val_tan)

Sine value [-0.98803162 -0.30481062  0.89399666]
Cosine value [ 0.15425145 -0.95241298 -0.44807362]
Tangent value [-6.4053312   0.32004039 -1.99520041]


In [8]:
import numpy as np
arr = np.array([30,60,90])
 
rad = np.deg2rad(arr)
print("Radian values for the array having degree values:", rad)
 
arr_rad = np.array([0.52359878, 1.04719755, 1.57079633])
degree = np.rad2deg(arr_rad)
print("Degree values for the array having radian values:", degree)

Radian values for the array having degree values: [0.52359878 1.04719755 1.57079633]
Degree values for the array having radian values: [30.00000025 59.99999993 90.00000018]


In [9]:
import numpy as np
arr = np.array([1,0.5])
 
sin_ang = np.arcsin(arr)
print("Angle from the sin function:", sin_ang)
 
cos_ang = np.arccos(arr)
print("Angle from the cos function:", cos_ang)
 
tan_ang = np.arctan(arr)
print("Angle from the tan function:", tan_ang)

Angle from the sin function: [1.57079633 0.52359878]
Angle from the cos function: [0.         1.04719755]
Angle from the tan function: [0.78539816 0.46364761]


In [10]:
import numpy as np
 
b = 5
h = 8
 
hy = np.hypot(b, h)
 
print(hy)

9.433981132056603


In [23]:
import numpy as np
arr = np.array([30,60,90])
 
val_sin = np.sinh(arr)
print("Hyperbolic Sine value",val_sin)
 
val_cos = np.cosh(arr)
print("Hyperbolic Cosine value",val_cos)
 
val_tan = np.tanh(arr)
print("Hyperbolic Tangent value",val_tan)

Hyperbolic Sine value [5.34323729e+12 5.71003695e+25 6.10201647e+38]
Hyperbolic Cosine value [5.34323729e+12 5.71003695e+25 6.10201647e+38]
Hyperbolic Tangent value [1. 1. 1.]


In [25]:
import numpy as np
a=np.array([(1,2,3),(1,2,3)])
print(a)
print(a.sum(axis=0))


[[1 2 3]
 [1 2 3]]
[2 4 6]
